lib/nc_time_axis/__init__.py, lib/nc_time_axis/tests/__init__.py, lib/nc_time_axis/tests/unit/__init__.py, lib/nc_time_axis/tests/unit/test_NetCDFTimeConverter.py, lib/nc_time_axis/tests/unit/test_NetCDFTimeDateFormatter.py, lib/nc_time_axis/tests/unit/test_NetCDFTimeDateLocator.py
This adds some unit tests.
In future I want to extend the unit testing for `NetCDFTimeConverter.axisinfo`, `NetCDFTimeConverter.default_units` and `NetCDFTimeDateFormatter` (specifically the `__call__ `method)
=> Add (almost all) unit tests

nc_time_axis/__init__.py, nc_time_axis/tests/unit/test_NetCDFTimeConverter.py, nc_time_axis/tests/unit/test_NetCDFTimeDateLocator.py, requirements.txt
To integrate this with Iris, we want to make use of the newer version of netcdf4.
New netcdf4 has slightly different behaviour, e.g. differing number results; not allowing you to add a calendar attribute to netcdftime.datetime object (See [PR6 comment ](https://github.com/SciTools/nc-time-axis/pull/6#issuecomment-229050703) for more detail)
This adds a container for the netcdftime.datetime object and associated calendar object, then registers that container with matplotlib.units instead.
=> Use container of nc datetime and calendar.

nc_time_axis/__init__.py, nc_time_axis/tests/unit/test_NetCDFTimeDateLocator.py
Whilst using flake8 on the code I noticed that hour/minute/second_unit wasn't being used.
Those units are there so that when you pick good values of ticks, you should do it in the correct unit rather than defaulting to "days since 2000"
=> Fix tick_values computation units

nc_time_axis/__init__.py, nc_time_axis/tests/unit/test_NetCDFTimeDateLocator.py, requirements.txt
this is a subtle bug
for certain configurations of python and numpy 
```
calendars[0] == calendars
```
returns `False`, whilst
```
calendars == calendars[0]
```
returns `array([ True,  True,], dtype=bool)`
therefore
```
np.all(calendars[0] == calendars)
```
returns `False`, whilst 
```
np.all(calendars == calendars[0])
```
returns `True`
as type coercion, where it occurs, tends to happen left to right, this order is safer
=> fix compare bug

README.rst
Forgot this part when I submitted #30
=> update readme to mention cftime

nc_time_axis/__init__.py, nc_time_axis/tests/integration/test_plot.py, nc_time_axis/tests/unit/test_NetCDFTimeConverter.py
We would love to use nc-time-axis in xarray.  There was [some discussion over the summer](
https://github.com/pydata/xarray/issues/2164#issuecomment-404830736) about possibly adding support for plotting subclasses of `cftime.datetime` (e.g. `cftime.DatetimeNoLeap`) directly.  This would make using it in xarray somewhat easier.  This PR is an attempt to add that.  In so doing, I've retained support for plotting `nc_time_axis.CalendarDateTime` objects, so this should be backwards-compatible.
Let me know if there is still interest in this.  I'm happy to iterate on it if desired.
For example, with this PR one can now do something like this:
```python
import random
import matplotlib.pyplot as plt
import nc_time_axis
import cftime
d_time = [cftime.Datetime360Day(year=2017, month=2, day=n) for n …
```
=> Add support for plotting subclasses of cftime.datetime

nc_time_axis/__init__.py, nc_time_axis/tests/unit/test_NetCDFTimeDateLocator.py
Towards fixing #44. 
@spencerkclark I was not sure how to add tests for this. Is there an example that you could point me to?
=> Remove year 0 ticks if generated

.pre-commit-config.yaml, README.md
After migrating the `master` branch to `main`, this PR tidies up some dangling references to `master` in the repo.
This is the last PR before tagging and releasing 1.3.0
=> change references of master to main

requirements/py37.yml, requirements/py38.yml, requirements/py39.yml, setup.cfg
This PR introduced a minimum pin of `cftime>=1.5`, otherwise it is possible for `nc-time-axis` 1.13.0 to be resolved with an incompatible version of `cftime` within a `conda`/`pip` environment
=> min pin for cftime

nc_time_axis/__init__.py, nc_time_axis/tests/integration/test_plot.py, nc_time_axis/tests/unit/test_NetCDFTimeConverter.py
Fixes #47 and fixes #74. Now `NetCDFTimeConverter.convert` accepts lists or tuples, as given by matplotlib when using `fill_between` and `axhspan` (and maybe others).
Added a unit test and an integration one.
=> Fix NetCDFTimeConverter.convert with list

nc_time_axis/__init__.py, nc_time_axis/tests/unit/test_NetCDFTimeDateFormatter.py
This takes a fairly simple approach to addressing #48.  Here I define a mapping between the resolution chosen by the tick locator depending on the range and number of ticks requested, and the date format for the labels on the axis.  
The plot @klindsay28's example now produces is shown below:
=> Harmonize label format and tick resolution choosing logic

README.md, nc_time_axis/__init__.py, nc_time_axis/tests/integration/test_plot.py, nc_time_axis/tests/unit/test_NetCDFTimeConverter.py, nc_time_axis/tests/unit/test_NetCDFTimeDateLocator.py
Addresses #75.  I think we can probably close #16 as well.
This makes it possible to plot cftime's universal datetime object, which was introduced in cftime 1.3.0.  The following example now works:
```python
import random
import cftime
import matplotlib.pyplot as plt
import nc_time_axis
dt = [cftime.datetime(2017, 2, day, calendar="noleap") for day in range(1, 28)]
temperatures = [round(random.uniform(0, 12), 3) for _ in range(len(dt))]
plt.plot(dt, temperatures)
```
We will raise a `ValueError` if someone tries to plot dates without a specified calendar.
I have taken the liberty to update the example in the README to follow this approach, because it is simpler than using `CalendarDateTime`.  Since nc-time-axis now requires cftime >= 1.5 (https://github.com/SciTools/nc-time-axis/pull/69), …
=> Add support for plotting universal datetime objects

nc_time_axis/__init__.py, nc_time_axis/tests/integration/test_plot.py, nc_time_axis/tests/unit/test_AutoCFTimeFormatter.py, nc_time_axis/tests/unit/test_CFTimeFormatter.py, nc_time_axis/tests/unit/test_NetCDFTimeDateLocator.py
This implements the proposal outlined in https://github.com/SciTools/nc-time-axis/issues/41#issuecomment-898895834.
The following example now works.  Here I am setting a single tick on the x-axis and labeling it with a date format of `"%Y-%m"` using the newly added `CFTimeFormatter`:
```python
import random
import cftime
import matplotlib.pyplot as plt
import nc_time_axis
dt = [cftime.DatetimeNoLeap(2017, 2, day, calendar="noleap") for day in range(1, 28)]
temperatures = [round(random.uniform(0, 12), 3) for _ in range(len(dt))]
fig, ax = plt.subplots(1, 1)
ax.plot(dt, temperatures)
ax.set_xticks([cftime.DatetimeNoLeap(2017, 2, 10)])
ax.xaxis.set_major_formatter(nc_time_axis.CFTimeFormatter("%Y-%m", "noleap"))
```
The `NetCDFTimeDateFormatter` has been renamed to `AutoCFTimeFormatter`. …
=> Add ability to set ticks and tick label format

nc_time_axis/__init__.py, nc_time_axis/tests/integration/test_plot.py, nc_time_axis/tests/unit/test_CalendarDateTime.py, nc_time_axis/tests/unit/test_NetCDFTimeConverter.py
Closes #81
This adds a `DeprecationWarning` to the `CalendarDateTime` constructor, which will allow us to remove it in nc-time-axis version 1.5.  These warnings are ignored when running our test suite to reduce noise.
=> Deprecate `CalendarDateTime`

docs/release-notes.rst
I forgot to add a note to the release notes in #87; this corrects that.
=> Add release note for deprecation of CalendarDateTime

.cirrus.yml
From @rcomer: the latest version of `conda-lock` creates lockfiles by default that cannot be used to generate environments with conda/mamba.  Using the `-k explicit` option restores the old behavior.  
See also: SciTools/iris#4644.
=> Use the `-k explicit` option when creating lockfiles in CI

.cirrus.yml, .readthedocs.yml, docs/installation.rst, pyproject.toml, requirements/docs.yml, requirements/ncta.yml, requirements/py310.yml, requirements/py311.yml, setup.cfg
This PR increases the supported python versions to 3.9-3.11.  Support for v3.8 was due to end last week according to NEP29 recommendations.
https://numpy.org/neps/nep-0029-deprecation_policy.html
The tests pass for me locally under python 3.11.  The doc build failed under both 3.9 and 3.11, so let's see what readthedocs does...
=> Bump python versions

.github/workflows/ci-wheels.yml
This pull-request replaces #186 and #187.
Migrating to the next version (`@3` -> `@4`) requires to be done consistently within a single pull-request for both of the `upload-artifact` and `download-artifact` GHAs.
=> bump download/upload artifact gha version

docs/release-notes.rst, requirements/py310.yml, requirements/py311.yml, requirements/py39.yml, requirements/pypi-core.txt
This pull-request enforces `nep29` and drops `numpy 1.22`, as scheduled.
See [NEP29 Drop Schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule).
=> nep29 drop numpy 1.22

CONTRIBUTING.md
See SciTools/.github#19 for more details - saves me writing it out multiple times!
@spencerkclark @aulemahal you have been very kind to contribute so much time to nc-time-axis, but this is probably the first you are hearing about the CLA changes. Please take a moment to make sure you are comfortable; I don't imagine this PR moving until 2024.
=> Update contributing guidelines in line with v5 SciTools CLA

pyproject.toml
Small update to turn comment out the following:
```
[mypy] warn_unreachable=true
```
as that check is listed in the `disable_error_code` list for mypy.
This also requires the `MY103` check adding to the `ignore` list in `repo-review`.
This was supposed to go into PR #293 , but it got merged before I could update.
=> QA: Remove `warn_unreachable=true` from mypy config

.github/workflows/ci-tests.yml
A recent release of `Miniforge` has broke this CI the fix requires renaming `Mambaforge` to `Miniforge`
Propagating this fix over from python-stratify
SciTools/python-stratify#302
=> Mambaforge to Miniforge3

pyproject.toml, src/nc_time_axis/__init__.py, src/nc_time_axis/tests/unit/test_CFTimeFormatter.py
Ref: #297 
Fix Ruff A002 linter warnings (variable shadows builtin) with `noqa` directives.
=> Fix Ruff A002 linter warning

pyproject.toml, requirements/py311.yml, requirements/py312.yml, requirements/py313.yml
This pull-request complies with [PEP639](https://peps.python.org/pep-0639/) for `setuptools`, also see [license and license-files](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files).
Additionally avoids the following `setuptools` deprecation warning:
```
!!
********************************************************************************
Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: BSD License
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
!!
```
=> pep639: setuptools license and license-files fields
